### PR TITLE
Use correct scala-compiler dependency for Scala 3

### PR DESCRIPTION
**Pull request by FunFunFine**
Check out #60 for description.

### CODE REVIEW

**Review by edmorley — COMMENTED** [review]
(Switching any reviews that need language-owner review to the owner directly, to prevent reminders the rest of the team can't action. Sadly GitHub won't allow removing a CODEOWNERS review request without leaving a review)

**Comment by y-yu** [comment]
Is `scala-compiler` dependency really needed? 🤔 I removed `scala-compiler` dependency in #57 , it seems to work well.

**Comment by ndeverge** [comment]
Hello,

Could someone check and merge this PR? It prevents us to migrate our project to Scala3.

**Comment by Malax** [comment]
Hey @ndeverge - we are about to sunset this plugin (as well as the Gradle and Maven plugins). It's unlikely that we will merge and release this PR.

Can you share your use-case for using the plugin? I know that some folks need to deploy JAR files directly from in-house CI due to compliance reasons. We have a semi-new tool for that use-case that we intent to maintain long-term: [heroku-jvm-application-deployer](https://github.com/heroku/heroku-jvm-application-deployer). Can you give that a try?

**Comment by ndeverge** [comment]
@Malax thanks for getting back to me.
I used the plugin so that my CI deploys my apps on Heroku (so I don't have to do this manually), and I just have to set the deploy config in my build.sbt file (Heroku instance name, JdkVersion etc.).
I quickly checked [heroku-jvm-application-deployer](https://github.com/heroku/heroku-jvm-application-deployer), but it seems it needs to be used from the command line, right?

**Comment by ndeverge** [comment]
@Malax Thanks for the suggestion. I'll do that since the sbt plugin is not maintained anymore.

**Comment by Malax** [comment]
@ndeverge, don't hesitate to open an issue in that other repo should you have trouble. Happy to help!

**Comment by Malax** [comment]
Closing this PR because this repository will be archived. See https://github.com/heroku/heroku-jvm-application-deployer for an alternative CLI to deploy locally compiled Scala applications.

**Pull request closed without merging**
